/* ---------- catalog: Tier 1 + Tier 2 from Skiply_Footwear_Assessment_Spec_v1 ---------- */
export const CAT = [
 // brand, model, CLIP visual label, years, msrp, demand, category, repairable
 ["Nike","Air Jordan 1 High","Nike Air Jordan 1 high-top basketball sneaker with swoosh","1985–present",180,1.35,"sneaker-high",0],
 ["Nike","Air Jordan 4","Nike Air Jordan 4 basketball sneaker with mesh panels and wing eyelets","1989–present",215,1.40,"sneaker-high",0],
 ["Nike","Dunk Low","Nike Dunk low-top sneaker with color blocked panels and swoosh","1985–present",115,1.25,"sneaker-low",0],
 ["Nike","Air Force 1 '07","Nike Air Force 1 low white leather sneaker with swoosh","1982–present",115,1.15,"sneaker-low",0],
 ["Nike","Air Max 90","Nike Air Max 90 sneaker with visible air bubble in heel","1990–present",130,1.00,"runner",0],
 ["Nike","Air Max 270","Nike Air Max 270 sneaker with large heel air unit","2018–present",160,0.90,"runner",0],
 ["Nike","Pegasus","Nike Pegasus mesh running shoe with swoosh","2020s",140,0.80,"runner",0],
 ["Nike","Blazer Mid","Nike Blazer mid vintage style sneaker with large swoosh","1973–present",105,0.95,"sneaker-high",0],
 ["Adidas","Samba OG","Adidas Samba low-profile indoor soccer shoe with three stripes and gum sole","1950–present",100,1.30,"sneaker-low",0],
 ["Adidas","Gazelle","Adidas Gazelle suede sneaker with three stripes","1966–present",100,1.20,"sneaker-low",0],
 ["Adidas","Campus 00s","Adidas Campus suede sneaker with three stripes chunky sole","2023–present",110,1.10,"sneaker-low",0],
 ["Adidas","Superstar","Adidas Superstar shell-toe sneaker with three stripes","1969–present",100,0.85,"sneaker-low",0],
 ["Adidas","Stan Smith","Adidas Stan Smith white leather tennis sneaker","1971–present",100,0.80,"sneaker-low",0],
 ["Adidas","Ultraboost","Adidas Ultraboost knit running shoe with boost foam sole","2015–present",190,0.85,"runner",0],
 ["Adidas","Yeezy Boost 350","Adidas Yeezy Boost 350 knit sneaker","2015–2022",230,1.20,"runner",0],
 ["New Balance","550","New Balance 550 retro basketball sneaker with N logo","2020–present",120,1.15,"sneaker-low",0],
 ["New Balance","990 series","New Balance 990 grey suede mesh running shoe with N logo","1982–present",200,1.10,"runner",0],
 ["New Balance","9060","New Balance 9060 chunky lifestyle sneaker with N logo","2022–present",150,1.10,"runner",0],
 ["New Balance","574","New Balance 574 classic suede sneaker with N logo","1988–present",90,0.80,"runner",0],
 ["On","Cloud 5","On Cloud running shoe with hollow cloudtec pod sole","2019–present",140,0.85,"runner",0],
 ["On","Cloudmonster","On Cloudmonster thick foam running shoe with pod sole","2022–present",170,0.90,"runner",0],
 ["Hoka","Clifton","Hoka Clifton thick cushioned running shoe with oversized midsole","2014–present",145,0.90,"runner",0],
 ["Hoka","Bondi","Hoka Bondi maximal cushion running shoe with huge midsole","2011–present",165,0.90,"runner",0],
 ["Hoka","Speedgoat","Hoka Speedgoat trail running shoe with lugged outsole","2015–present",155,0.95,"runner",0],
 ["Asics","Gel-Kayano","Asics Gel-Kayano stability running shoe with gel cushioning","1993–present",160,0.85,"runner",0],
 ["Asics","GT-2160","Asics GT-2160 retro y2k running shoe silver accents","2023–present",110,1.05,"runner",0],
 ["Asics","Gel-1130","Asics Gel-1130 retro running shoe with mesh and silver overlays","2023–present",100,1.10,"runner",0],
 ["Brooks","Ghost","Brooks Ghost cushioned mesh running shoe","2018–present",140,0.80,"runner",0],
 ["Brooks","Adrenaline GTS","Brooks Adrenaline supportive mesh running shoe","2018–present",140,0.75,"runner",0],
 ["Allbirds","Tree Runner","Allbirds Tree Runner minimalist knit sneaker plain","2019–present",98,0.60,"casual",0],
 ["Allbirds","Wool Runner","Allbirds Wool Runner soft wool sneaker plain","2016–present",110,0.60,"casual",0],
 ["Converse","Chuck Taylor All Star","Converse Chuck Taylor canvas high-top sneaker with rubber toe cap","1957–present",65,0.75,"sneaker-high",0],
 ["Converse","Chuck 70","Converse Chuck 70 premium canvas sneaker with rubber toe cap","2013–present",90,0.90,"sneaker-high",0],
 ["Vans","Old Skool","Vans Old Skool skate shoe with side stripe and waffle sole","1977–present",70,0.80,"sneaker-low",0],
 ["Puma","Suede Classic","Puma Suede Classic sneaker with formstrip","1968–present",75,0.70,"sneaker-low",0],
 ["Reebok","Club C 85","Reebok Club C white leather tennis sneaker","1985–present",90,0.80,"sneaker-low",0],
 ["Salomon","XT-6","Salomon XT-6 technical trail running shoe with quicklace","2013–present",200,1.10,"runner",0],
 // Tier 2 — premium repairable (NuShoe core)
 ["Red Wing","Iron Ranger","Red Wing Iron Ranger leather cap-toe work boot with welted sole","1905–present",350,1.05,"boot",1],
 ["Red Wing","Classic Moc","Red Wing Classic Moc toe leather boot with white wedge sole","1952–present",330,1.00,"boot",1],
 ["Timberland","6-Inch Premium","Timberland wheat nubuck 6 inch waterproof boot","1973–present",198,0.90,"boot",1],
 ["Dr. Martens","1460","Dr Martens 1460 leather boot with yellow stitching","1960–present",170,0.90,"boot",1],
 ["Blundstone","550","Blundstone leather chelsea boot with elastic sides","1968–present",230,0.95,"boot",1],
 ["Ecco","Leather Shoe","Ecco leather comfort shoe","1990s–present",200,0.80,"casual",1],
 ["Mephisto","Walking Shoe","Mephisto leather walking shoe","1980s–present",330,0.75,"casual",1],
 ["Johnston & Murphy","Dress Shoe","Johnston and Murphy leather dress shoe oxford","1990s–present",180,0.60,"dress",1],
 ["Merrell","Moab","Merrell Moab hiking shoe with lugged sole","2007–present",135,0.75,"boot",1],
 // Tier 3 / other
 ["Birkenstock","Boston","Birkenstock Boston suede clog with cork footbed","1979–present",165,1.10,"sandal",0],
 ["Birkenstock","Arizona","Birkenstock Arizona two-strap cork sandal","1973–present",110,1.00,"sandal",0],
 ["UGG","Classic","UGG classic sheepskin boot tan","1978–present",170,1.00,"boot",0],
 ["Crocs","Classic Clog","Crocs foam clog with holes","2002–present",50,0.80,"sandal",0],
 ["Generic","Running Shoe (other)","generic mesh running shoe athletic sneaker","—",120,0.60,"runner",0],
 ["Generic","Canvas Sneaker (other)","plain canvas sneaker","—",60,0.55,"sneaker-low",0],
 ["Generic","Leather Dress Shoe (other)","leather dress shoe","—",140,0.50,"dress",1],
 ["Generic","Work Boot (other)","leather work boot","—",180,0.70,"boot",1],
 ["Generic","Sandal (other)","casual sandal","—",60,0.50,"sandal",0],
].map((r,i)=>({id:i,brand:r[0],model:r[1],label:r[2],years:r[3],msrp:r[4],demand:r[5],cat:r[6],rep:!!r[7]}));

export const COND = [
 {label:"a brand new pristine unworn shoe with clean sole", grade:"A", word:"Like new",  score:92},
 {label:"a lightly used shoe in excellent condition with minimal wear", grade:"B", word:"Gently used", score:76},
 {label:"a moderately worn used shoe with visible creasing scuffs and sole wear", grade:"C", word:"Worn", score:52},
 {label:"a heavily worn beat up shoe with major damage and worn out sole", grade:"D", word:"Damaged", score:22},
 {label:"a destroyed shoe with holes mold stains or separated sole", grade:"D", word:"Damaged · flag", score:10, flag:true},
];
